steps:
  - label: ":eslint: Lint"
    command:
      - "npm install"
      - "npm run lint"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":nodejs: 10 :mocha: Unit/Integration Test"
    command:
      - "npm install"
      - "npm run build"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          image: "node:10"

  - label: ":nodejs: 12 :mocha: Unit/Integration Test"
    command:
      - "npm install"
      - "npm run build"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":nodejs: 12 :postgres: 11 :mocha: Postgres Test "
    plugins:
      - docker-compose#v2.1.0:
          run: testenv
          config:
            - .buildkite/docker-compose.postgres.yml

  # Borrowed from https://github.com/matrix-org/synapse/blob/master/.buildkite/pipeline.yml
  - label: ":newspaper: Newsfile"
    branches: "!master !develop !release-*"
    command:
      - "python3 -m pip install towncrier"
      - "python3 -m towncrier.check --compare-with=origin/develop"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          propagate-environment: true